practice-app/back-end/package-lock.json, practice-app/back-end/package.json, practice-app/back-end/src/api/routes/events.js, practice-app/back-end/src/api/routes/events.test.js, practice-app/back-end/src/config.js, practice-app/back-end/src/index.js, practice-app/back-end/src/services/eventService.js, practice-app/back-end/src/services/geoLocation.js
Event filter endpoint created. It takes two parameters radius and place and fetches filtered events with given parameters.
place => s.t New York, Seattle, Texas
radius => s.t 5 km
URL => events/filter?radius=5&place=Seattle
=> Event filter

practice-app/back-end/package.json, practice-app/back-end/test/test_scholars.js
Created scholars unit tests
Details are in the commit notes
=> Scholar test

practice-app/front-end/.env, practice-app/front-end/src/components/login.component.js, practice-app/front-end/src/components/registration.component.js, practice-app/front-end/src/config.js
api url changed to be fetched from .env
=> .env configuration

practice-app/back-end/src/api/routes/users.js, practice-app/back-end/src/models/user.js, practice-app/back-end/test/test_register.js
Topics added to registration,
topics added to unit test
=> Topics added to registration unit test also added

practice-app/API_DOCUMENTATION.md, practice-app/back-end/.eslintrc.json, practice-app/back-end/package-lock.json, practice-app/back-end/package.json, practice-app/back-end/src/api/routes/events.js, practice-app/back-end/src/config.js, practice-app/back-end/src/database/index.js, practice-app/back-end/src/database/mock.js, practice-app/back-end/src/services/eventService.js, practice-app/back-end/src/services/geoLocation.js, practice-app/back-end/test/events.test.js, practice-app/front-end/package-lock.json, practice-app/front-end/yarn.lock
* I've added a mechanism that uses a temporary database instead of real database during unit tests. 
* This causes a test failure in login with correct credentials, since database is empty initially. This testcase should be changed accordingly.
(Note: Since I've accidentally approved pull request containing the changes in events/filter, which is merged to master, these changes occur here.)
=> Tests mock db

practice-app/back-end/package.json, practice-app/back-end/src/api/routes/scholars.js, practice-app/back-end/test/test_scholars.js
- Fixed get single scholar endpoint
- Fixed updating a scholar endpoint
- Changed test_scholars.js according to these fixes
With Mahir
=> Fixed scholars endpoints and unit tests

practice-app/back-end/.vscode/launch.json, practice-app/back-end/src/api/routes/test.js, practice-app/back-end/src/api/routes/users.js, practice-app/front-end/.env, practice-app/front-end/package-lock.json, practice-app/front-end/package.json, practice-app/front-end/src/components/home.component.js, practice-app/front-end/src/components/paperapi.component.js, practice-app/front-end/src/helpers/requestHelper.js, practice-app/front-end/src/index.css
* I Converted some responses from plain text to JSON
* I added topics field in endpoint that returns all users.
=> Response update

practice-app/front-end/.env, practice-app/front-end/package-lock.json, practice-app/front-end/package.json, practice-app/front-end/src/components/home.component.js, practice-app/front-end/src/components/paperapi.component.js, practice-app/front-end/src/helpers/requestHelper.js, practice-app/front-end/src/index.css
* isomorphic-unfetch is used instead of axios
* Get, Post, Put, Patch, Delete requests can be done from ui
* Some style changes
=> Request support

.github/issue_template.md
I request some changes on the issue template. @buseg can you review it?
=> Update some wording in the issue template.

android/.idea/codeStyles/Project.xml, android/.idea/gradle.xml, android/.idea/jarRepositories.xml, android/.idea/misc.xml, android/.idea/vcs.xml, android/app/build.gradle, android/app/dependencies.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/bounswe2020group3/paperlayer/BasePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/BaseView.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/DependencyInjector.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/DependencyInjectorImpl.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/LoginFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/MainActivity.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/MainContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/MainFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/MainPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/RegisterFragment.kt, android/app/src/main/res/layout/activity_main.xml, android/app/src/main/res/layout/fragment_login.xml, android/app/src/main/res/layout/fragment_main.xml, android/app/src/main/res/layout/fragment_register.xml, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties
Implemented MVP architecture and added necessary dependencies
=> Create MVP architecture

android/app/build.gradle, android/app/src/main/java/com/bounswe2020group3/paperlayer/MainActivity.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfilePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectFragment.kt, android/app/src/main/res/layout/fragment_profile.xml, android/app/src/main/res/layout/fragment_project.xml, android/app/src/main/res/menu/bottom_nav_menu.xml, android/app/src/main/res/navigation/main_navigation.xml
=> [android] Navigate with bottom navigation

backend/api/urls.py, backend/api/views/auth.py
- The user id is returned from auth endpoint in "id" field
=> User id on auth response

.gitignore, android/app/build.gradle
=> Add material components dependency

.gitignore, android/app/build.gradle, android/app/src/main/java/com/bounswe2020group3/paperlayer/MainActivity.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfilePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/RegisterContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/RegisterFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/RegisterPresenter.kt, android/app/src/main/res/layout/fragment_profile.xml, android/app/src/main/res/layout/fragment_project.xml, android/app/src/main/res/layout/fragment_register.xml, android/app/src/main/res/menu/bottom_nav_menu.xml, android/app/src/main/res/navigation/main_navigation.xml, backend/api/urls.py, backend/api/views/auth.py
I have created a sufficient register fragment for now. Please review and evaluate
=> Android register

android/app/src/main/java/com/bounswe2020group3/paperlayer/login/LoginContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/login/LoginFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/login/LoginPresenter.kt, android/app/src/main/res/layout/fragment_login.xml, android/app/src/main/res/values/strings.xml
=> fragment_login.xml: Updated according to material-ui components.

backend/api/serializers/auth.py, backend/api/views/auth.py
Register now accepts 'first_name'. 'middle_name', 'last_name' and creates a new profile for the user using those names.
=> Register now accepts name fields

backend/Procfile, backend/api/serializers/auth.py, backend/backend/settings.py, backend/poetry.lock, backend/pyproject.toml
I added Procfile for the Heroku deployment configuration and some packages to pyproject.toml
=> Heroku deployment configuration

.github/workflows/backend-heroku.yml, backend/poetry.lock
I added a yml file for deployment to Heroku.
=> heroku action configuration for backend

backend/Dockerfile
Added PostgreSQL to dockerfile.
=> postgresql is added to dockerfile

front-end/src/Views/RegistrationPage.js
First, middle and last names are added to registration
=> names added to registration

.github/workflows/backend-heroku.yml
Heroku action will work only when every push action into the master branch.
=> Action trigger configuration changed

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/bounswe2020group3/paperlayer/network/RetrofitProvider.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfilePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/data/Gender.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/data/Profile.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/util/Constants.kt, android/app/src/main/res/layout/fragment_profile.xml
- Implement retrofit instance builder
- Add example api request with profile data
Fixes #220
=> Implement retrofit

front-end/src/Components/Auth/Authenticate.js, front-end/src/Views/LoginPage.js, front-end/src/Views/RegistrationPage.js
Logging in now also stores the id which will be used in later calls.
=> Login with id

.github/workflows/frontend-docker.yml, .github/workflows/frontend-npm.js.yml, android/.idea/dictionaries/app.xml, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/CreateUserService.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/RegisterFragment.kt, android/app/src/main/res/layout/activity_main.xml, android/app/src/main/res/layout/fragment_register.xml, android/app/src/main/res/navigation/main_navigation.xml, android/app/src/main/res/values/strings.xml, android/app/src/main/res/values/styles.xml, front-end/Dockerfile, front-end/src/index.js
I had some problems with the previous commits. I added some error checking mechanisms, and enhanced, updated my project to material-ui decision of my group.
=> Android register new

backend/api/views/profile.py, backend/api/views/project.py, backend/backend/settings.py, backend/poetry.lock, backend/pyproject.toml
Added django-filters to the project for easy filtering and automated Swagger page generation. 
Added query parameter of owner_id for profile and projects.
Solves: #254 #265
=> Added django_filters for easy filtering

.github/workflows/backend-aws-cd.yml, backend/Dockerfile, backend/docker-compose.yml, backend/task-definition.json
I added some files for AWS deployment. The port of the docker is changed to 80
=> Aws deployment for backend repo

android/app/src/main/java/com/bounswe2020group3/paperlayer/register/CreateUserService.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/RegisterContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/RegisterFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/RegisterModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/RegisterPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/register/data/Register.kt, android/app/src/main/res/layout/fragment_register.xml
I have connected the register to the backend, furthermore upgraded the navigation of the register page
=> Connecting register page to backend

front-end/src/Views/HomePage.js, front-end/src/config.js
=> Issue #250 home page

front-end/src/Views/EventPage.js
Event page to view the details of an event
=> event page

front-end/src/Views/ProfilePage.js, front-end/src/config.js
=> Issue #296 profile page

backend/Dockerfile, backend/backend/settings.py, backend/docker/run-local.sh, backend/docker/run.sh, backend/task-definition.json
AWS postgresql database added.
=> Backend aws dockerfile

android/app/src/main/res/layout/fragment_register.xml
I have changed the locations of the error messages for better visual comfort.
=> Fragment design has been updated

android/app/src/main/java/com/bounswe2020group3/paperlayer/dagger/AppComponent.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/dagger/ProjectCreateModule.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/projectCreate/ProjectCreateContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/projectCreate/ProjectCreateFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/projectCreate/ProjectCreateModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/projectCreate/ProjectCreatePresenter.kt
Add user's token while sending project create request
=> Add dependency injection to project create page

.github/workflows/frontend-aws-cd.yml, front-end/Dockerfile, front-end/nginx/nginx.conf, front-end/package-lock.json, front-end/task-definition.json
I added task-definition.json and made some changes in Dockerfile.These are configurations for deployment.
=> task-definition and Dockerfile configuration added

backend/backend/tests/test_file.py, backend/backend/tests/test_media/test_file.txt
=> Backend file improvements

backend/backend/settings.py, backend/task-definition.json
I fixed the secret issue for EMAIL_HOST_PASSWORD. It will be taken from the os environment.
=> Backend secrets

backend/api/tests/test_milestone.py
=> Milestone test

front-end/src/Views/HomePage.js, front-end/src/config.js
Milestones are listed under the upcoming events list on homepage
=> Issue 331 milestones on homepage

front-end/src/Views/ProfilePage.js
Profile page and homepage are done-ish
=> Layout changes

front-end/src/Views/ProjectPage.js
sidebar, tags part, recommended users part, upcoming deadlines part and similar projects part are added. Also, design of the other parts are updated.
=> Issue345-Project Page Layout

backend/api/serializers/profile.py, backend/api/serializers/user.py, backend/api/views/file.py
=> Backend-Fixing mistakes of one of latest merges

front-end/package-lock.json, front-end/package.json, front-end/src/Views/ProfilePage.js
Partially done - Need more information from the back-end about how the data will be sent to the front-end
=> Profile privacy

backend/api/serializers/user.py
For now, user will contain full profile data. It will be updated and it will contain only permissioned data.
=> Backend user contains profile

front-end/src/App.js, front-end/src/Views/HomePage.js, front-end/src/Views/ProfilePage.js, front-end/src/Views/ProjectPage.js, front-end/src/config.js
Milestones added to the profile page. 
May need additional work for clipping long descriptions when showing the project abstracts. 
Fixes #387
=> Profile milestones

front-end/src/Views/LoginPage.js, front-end/src/Views/ProfilePage.js
Minor Code Clean-up in Login 
Fixes #319
=> Photo refresh in profile, console.logs removed

front-end/src/Views/CreateEventPage.js, front-end/src/Views/CreateProjectPage.js, front-end/src/Views/EventPage.js, front-end/src/Views/ProfilePage.js
We changed /profile to /profile/userid when showing profiles
yes profile/userid because query is made to the users endpoint  
Fixes #397
=> profile urls changed to profile/{id}

front-end/src/Views/ProfilePage.js
Added projects to a user's own profile page. 
You can click the project name to go to that project.  🚀 
Fixes #388
=> Projects listed in Profile

android/app/src/main/java/com/bounswe2020group3/paperlayer/MainActivity.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/EventFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/main/MainFragment.kt, android/app/src/main/res/menu/bottom_nav_menu.xml, android/app/src/main/res/navigation/main_navigation.xml
I've updated the navigation flow as such:
- Main page doesn't have bottom navigation bar
- After successfull login, it redirects to home page and navigation bar appears.
- Then you cannot go back to the main page again
=> Update navigation flow

android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/edit/ProfileEditFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/user/UserFragment.kt, android/app/src/main/res/layout/fragment_profile.xml, android/app/src/main/res/layout/fragment_profile_edit.xml, android/app/src/main/res/layout/fragment_user.xml, android/app/src/main/res/values/strings.xml
- Change age to birthday in these pages
- * Profile
- * Profile Edit
- * User
- Add authentication field to user-related endpoints
=> Android - Update pages related to profile and user

backend/api/views/profile.py
-Profile needs Json data instead of Html from data as Android team wanted.
-Uploading and updating profile picture is currently unavailable due to this change. It will be worked on.
=> Profile needs Json data instead of Form data

backend/api/serializers/following.py, backend/api/views/following.py, backend/backend/settings.py
There were problems with accept and unfollow. I fixed them by defining custum serializers.
=> Backend follow system --issues fixed

backend/api/views/project.py, backend/backend/tests/test_project.py
Project owner is added to members upon creation.
=> Added owner to members

backend/api/views/search.py
- Now, not looking for the followed profiles when the request comes from a guest user
**Details of the problem are in the linked issue.**
=> Fixed guest user search error

backend/api/serializers/following.py, backend/api/serializers/user.py, backend/api/utils.py, backend/api/views/following.py, backend/api/views/user.py
According to follow functionality, make these changes:
- Add 'req_to_user' filter parameter to follow requests
- Remove follow fields in user serializers
- Convert user id to user object in follow serializers
- Add 'is_following' and 'is_follower' fields to user serializers
=> Backend follow serializers

backend/api/serializers/user.py, backend/api/utils.py
- Add `is_follow_request_sent` field to user serializers
=> Update user serializer

backend/api/serializers/project.py, backend/api/views/profile.py
-If a profile_picture is not found, 404 is returned.
-Private projects serializer now returns 'state', 'project_type', 'tags'.
-Improved code readibility.
=> Backend project and profile fixes

backend/api/views/collaboration_request.py
Added check for users sending multiple requests to projects. Also added id field to post.
=> Added multiple request checks and id

backend/api/serializers/following.py, backend/api/views/following.py
=> added id field for follow request

backend/api/serializers/following.py
=> added id field for follow

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfilePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/user/UserFragment.kt
Make these changes:
- Select an image from gallery
- Upload the image for profile pictures
Doesn't contain
- Display the image in profile page
This pull request is built on top of PR #470 and will be merged after it.
=> Android profile picture

front-end/src/Views/EditProfilePage.js, front-end/src/Views/ProfilePage.js
* code clean up
* profile bar shown while displaying other users' profiles
=> Profile-Edit further updates

android/app/src/main/java/com/bounswe2020group3/paperlayer/home/HomeContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/HomeModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/MilestonePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/adaptors/ProjectAdaptor.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/cards/ProjectUpdateCard.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/data/CollaborateRequest.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/data/CollaborationRequest.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/data/ProjectShort.kt
There was a problem with the git's merge. It resolved the conflicts by deleting some of the changes. We had to handle it manually.
=> Merge Problem Resolved

backend/api/models/comment.py, backend/backend/urls.py
-Comments can now be at most 1000 characters.
-Profile pictures and other files can be accessed by their url.
=> Fixed some issues about Comment and profile_picture

front-end/src/Views/ProfilePage.js, front-end/src/config.js
Followers, following and active following requests lists added to Profile page
=> follow info on the profile page

.github/workflows/frontend-azure-cd.yml
=> change build arg of azure fronted CD yml file

android/app/build.gradle, android/app/src/main/java/com/bounswe2020group3/paperlayer/search/SearchContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/search/SearchFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/search/SearchModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/search/SearchPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/search/data/Search.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/search/data/SearchResponse.kt, android/app/src/main/res/layout/fragment_search.xml, android/app/src/main/res/navigation/main_navigation.xml
=> Search page connected to backend.

backend/api/serializers/user.py, backend/api/urls.py, backend/api/views/auth.py, backend/backend/settings.py, backend/poetry.lock, backend/pyproject.toml, backend/templates/verification_body.html, backend/templates/verification_body.txt, backend/templates/verification_confirm.html
- Sends an email to verify the user.
- Returns "is_active" with the UserFullSerializer, True when verified.
**Details are in the linked issue**
=> Implemented email verification 

android/app/src/main/java/com/bounswe2020group3/paperlayer/home/EventFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/HomeContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/HomeModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/MilestoneFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/MilestonePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/adaptors/MilestoneAdaptor.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/adaptors/ProjectAdaptor.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/cards/MilestoneCard.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/data/Milestone.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/data/MilestoneListWrapper.kt, android/app/src/main/res/layout/layout_list_item_milestone.xml, android/app/src/main/res/layout/layout_list_item_projectupdate.xml, android/app/src/main/res/navigation/main_navigation.xml
This pull request provides error-prevention for the recycler views of the events and recent projects fragment. Furthermore I implemented the homepage-milestones fragment upon the changes made in backend and other implementations.
What is implemented:
* Viewing the milestones of the user on the homepage's subpage.
* View the project of the milestone
* Some error prevention mechanisms
* A wrapper class for milestones, because it does return an object instead of a list
=> Android homepage milestones

backend/api/serializers/profile.py, backend/api/utils.py
Profile returns the id of the rating a user created on the accessed user.
=> Rating Improvements

backend/api/models/collaboration_invite.py, backend/api/serializers/collaboration_invite.py, backend/api/views/collaboration_invite.py
Changed the response of collaboration invite to be the same as GET response.
=> Changed the collaboration invite post response

backend/api/serializers/project.py
Owner_id field was added to the project after requests from Android.
=> Added owner_id field to project

android/app/src/main/java/com/bounswe2020group3/paperlayer/event/EventDetailPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/EventFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/EventPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/adaptors/EventAdaptor.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/cards/EventCard.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/data/Event.kt, android/app/src/main/res/layout/layout_list_item_event.xml
I implemented navigation connection from the homepage's events subpage to event details fragment.
=> Android event navigation connection

backend/api/serializers/profile.py
Added is_commentable field to profile serializer
=> Added is_commentable field to profile serializer

android/app/src/main/java/com/bounswe2020group3/paperlayer/home/MilestonePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InviteContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InviteFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InviteModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InvitePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/UserInviteAdapter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/data/ProjectShort.kt, android/app/src/main/res/layout/fragment_invite.xml, android/app/src/main/res/layout/fragment_project_detail.xml, android/app/src/main/res/navigation/main_navigation.xml
Invite feature added to the project details' members subpage.
=> Invite feature added to the project details' members subpage

backend/api/serializers/profile.py
Profile will now have an owner_id field where Anroid and Frontend can access the users
=> Added owner_id to profile

front-end/src/Components/ProfileBar/Profilebar.js, front-end/src/Views/EventPage.js
I changed the sidebar color, I think this looks better.
=> Sidebar Color is changed

backend/api/views/milestone.py
Added filter to take milestones of a given project id.
=> Added filter to take milestones of a project

android/app/src/main/java/com/bounswe2020group3/paperlayer/collaborationRequests/CollabAdaptor.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/collaborationRequests/CollabCard.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/collaborationRequests/CollabContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/collaborationRequests/CollabFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/collaborationRequests/CollabModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/collaborationRequests/CollabPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/dagger/AppComponent.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/dagger/CollaborationRequestModule.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/data/CollaborationRequest.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailFragment.kt, android/app/src/main/res/layout/fragment_collaboration_requests.xml, android/app/src/main/res/layout/fragment_project_detail.xml, android/app/src/main/res/layout/fragment_projectupdates.xml, android/app/src/main/res/layout/layout_list_item_collaborationrequest.xml, android/app/src/main/res/navigation/main_navigation.xml
Collaboration Request Reply System has been added to be used from the project details page.
What I implemented:
* I implemented a recyclerview to view all the collaboration requests send for this project.
* The owner can accept/reject the collaboration request as he sees fit.
* The owner can view the user of the certain request pressing on the request except accept or reject button.
=> Collaboration Request Reply System has been added

front-end/src/Components/ProfileBar/Profilebar.js, front-end/src/Views/EventPage.js, front-end/src/Views/HomePage.js, front-end/src/Views/ProfilePage.js, front-end/src/Views/ProjectPage.js
Added create an event button to profile bar, enabled redirect functionality on pages and removed from home page
=> Create an event button

android/app/src/main/java/com/bounswe2020group3/paperlayer/home/EventFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/adaptors/EventAdaptor.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/adaptors/MilestoneAdaptor.kt, android/app/src/main/res/drawable/gradient_item.xml, android/app/src/main/res/drawable/newgradient.xml, android/app/src/main/res/layout/fragment_milestones.xml, android/app/src/main/res/layout/layout_list_item_event.xml, android/app/src/main/res/layout/layout_list_item_milestone.xml
I have removed the view buttons from both events and milestones subpages of the homepage.
And also added gradient alternatives for later discussions.
=> Button Removal, and gradient alternatives

front-end/src/App.js, front-end/src/Components/TopBar/UserNavbar.js, front-end/src/Views/CreateEventPage.js, front-end/src/Views/CreateProjectPage.js, front-end/src/Views/EditProfilePage.js, front-end/src/Views/EditProjectPage.js, front-end/src/Views/EventPage.js, front-end/src/Views/HomePage.js, front-end/src/Views/IssueMilestonePage.js, front-end/src/Views/ProfilePage.js, front-end/src/Views/ProjectPage.js, front-end/src/Views/SearchPage.js, front-end/src/config.js
Search functionality was enabled on the user bar.
After each query, the result is shown on a Search Page. 
Search page was added to the route
=> Search bar

android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InviteCard.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InviteContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InviteFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InvitePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/UserInviteAdapter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/MemberCard.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/MembersAdapter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailFragment.kt, android/app/src/main/res/layout/fragment_project_detail.xml, android/app/src/main/res/layout/fragment_projectupdates.xml, android/app/src/main/res/navigation/main_navigation.xml
- Navigate to user fragment from invite list
- Navigate to user fragment from members list
- Fix layout of project detail
=> Android navigate to user

android/app/src/main/java/com/bounswe2020group3/paperlayer/home/HomeContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/adaptors/ProjectAdaptor.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/cards/ProjectUpdateCard.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectModel.kt, android/app/src/main/res/layout/fragment_project_detail.xml
To synchronise the data flow between I had to make some iternal changes on the recentProjects page:
Change a card value from boolean to int.
Added a map to control the already requested projects.
Added a seperate collaboration service to the project details.
What I haven't implemented yet:
The only proper way to use this collaborate button is through recentProjects page. I haven't implemented inner services for it to use, in the cases of coming here from other fragments.
=> A collaborate button has been added to

android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectModel.kt, android/app/src/main/res/layout/fragment_project_detail.xml
This is @mhrfky 's work on fixing a bug about collaboration requests. I've fixed merge conflicts on my local and opened a pull request.
=> Android collaborate button on project details page

android/app/src/main/java/com/bounswe2020group3/paperlayer/collaborationRequests/CollabAdaptor.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/collaborationRequests/CollabPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/MemberCard.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/MembersAdapter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailFragment.kt, android/app/src/main/res/layout/fragment_profile.xml, android/app/src/main/res/layout/fragment_project_detail.xml, android/app/src/main/res/layout/layout_list_item_collaborationrequest.xml, android/app/src/main/res/layout/layout_list_item_project_member.xml
- Update invite list items
- Update member list items
- Add scrollview to profile fragment
- Move collaboration request button under the title of project, in project detail fragment
=> Android UI updates

android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectsContract.kt
When clicked on collaboration request button and pressed back, tags on project detail page were duplicated, that bug is fixed
There was not authentication of user on projects page which caused problems on current user's private projects, fixed
Some code improvements on project page
=> Android - Add authentication to projects page and some bug fixes

android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailFragment.kt
Fixed string check of project state on project detail fragment
=> Fix project state on project detail fragment

android/app/src/main/java/com/bounswe2020group3/paperlayer/util/Constants.kt
Use azure deployment URL for API requests.
=> Constants.kt: Use azure URL

backend/api/serializers/following.py, backend/api/serializers/notification.py
follow_request serializer bug fixed
=> Backend notification

front-end/src/Views/SearchPage.js
- showing user's full name on profile bar
- showing tags of the project on search page
- shorter description of the project on search page
these features are handled
=> Search page frontend

front-end/src/App.js, front-end/src/Components/TopBar/PrimarySearchAppBar.js, front-end/src/Views/LoginPage.js, front-end/src/Views/RegistrationPage.js, front-end/src/Views/TermsOfServicesPage.js
Guest users can now search and access the search page. 
Fixes #586
=> Guest user search added

front-end/src/App.js, front-end/src/Components/Auth/Authenticate.js, front-end/src/Components/Date/DateComponent.js, front-end/src/Components/ProfileBar/Profilebar.js, front-end/src/Components/TopBar/PrimarySearchAppBar.js, front-end/src/Components/TopBar/UserNavbar.js, front-end/src/Views/CreateEventPage.js, front-end/src/Views/CreateProjectPage.js, front-end/src/Views/EditProfilePage.js, front-end/src/Views/EditProjectPage.js, front-end/src/Views/EventPage.js, front-end/src/Views/FileViewerPage.js, front-end/src/Views/HomePage.js, front-end/src/Views/IssueMilestonePage.js, front-end/src/Views/ProfilePage.js, front-end/src/Views/ProjectPage.js
Sorry for a relatively big PR: 
* Request headers can be imported from Auth.js with function getRequestHeader() 
* Guest users can now access: Search page, homepage, profile pages, project pages, and event pages. 
* Navbar changed so that it will show login and register for guest users instead of logout and profile page.
* Profile side bar changed to render nothing if the user is not logged in. 
* Milestones do not show in the homepage if the  if the user  isn't logged in. 
* Comments and ratings of private profiles can be seen by guest users and people that do not follow them for more transparency.
These features may need extensive testing, I have done some of my own but it probably wouldn't hurt. 
Fixes #608
=> Guest user mode

backend/api/views/project.py, backend/api/views/user.py
Count limit is added with an optional parameter to both user and project recommendations
=> Added optional count limit for recommendations

front-end/src/Views/HomePage.js
We now have pagination in the projects listed in the homepage hooray
Fixes #612
=> pagination for projects added to the homepage

backend/api/views/user.py
-Users can be gotten by their username
=> Added filter to get user by username

backend/api/views/search.py
Added sorting for projects with respect to the project owner rating, match with user expertise, and whether the searching user follows any of the members. Also added sorting for users with respect to their rating and whether the searching user follows anyone who follows the user being searched.
Projects are sorted according to the following formula:
* (1 + number of requirements matching with user expertise) * ( 1 + (project owner rating/10)) * (if user is a member of the project 5 else if user follows any of the project members 1.5 else 1)
Users are sorted according to the following formula:
* ( 1 + (project owner rating/10)) * (if the searched user is followed by the user 5 else if the searched user is followed by anyone who is followed by the user 3 else 1)
=> Search sort

android/app/src/main/java/com/bounswe2020group3/paperlayer/home/EventFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/MilestoneFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/RecentProjectsFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/home/adaptors/ProjectAdaptor.kt, android/app/src/main/res/layout/layout_list_item_event.xml, android/app/src/main/res/menu/top_nav_menu.xml
I changed event card view's design with giving more spaces between the texts.
ProjectUpdate card is now clickable. No need to click on the view..
I added some commented codes for later design issues.
=> Simple design changes

android/app/src/main/java/com/bounswe2020group3/paperlayer/dagger/AppComponent.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/dagger/InviteModule.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InviteContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InviteModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/InvitePresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/ManageInvitesContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/ManageInvitesFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/ManageInvitesPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectDetailFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/util/Constants.kt, android/app/src/main/res/layout/fragment_project_detail.xml, android/app/src/main/res/navigation/main_navigation.xml
I have added the recommendation system in the project invite. To reduce the confusion and to give the user more control, I have created a seperate part to manage one's invitations. With that if one has already invited first 10 people, he does not have scroll down to invite others. All sent invitations can be handled in a seperate part.
=> Android invite recommendation implementation

backend/api/views/project.py
A really small bug with integer casting was fixed
=> Fixed bug with casting

front-end/src/Views/HomePage.js, front-end/src/Views/ProjectPage.js
Clicking on members in project page forwards to their profiles.
Fixes #614
=> Clicking on members in project page forwards to their profiles

front-end/src/Components/TopBar/UserNavbar.js
I was able to test these features in @emirhanyasin 's collaboration branch, so I implemented them. Now all notifications are visible in the front-end.
=> [Frontend] Collaboration & Comment Requests Notifications are Implemented

backend/api/views/project.py, backend/api/views/publication.py
Following the request from @mhrfky the projects were sorted in reverse order.
=> Reversed the sort for default

backend/api/views/search.py
One commit by @alifurkanbudak was overwritten, fixed that problem.
=> Fixed overwrited search view

front-end/src/Components/ProfileBar/Profilebar.js, front-end/src/Views/ProfilePage.js, front-end/src/Views/ProjectPage.js
Gap between navbar and sidebar are removed. Thanks to @liberbey 's suggestion
**Pages :**
* Own profile page,
* project pages 
Fixes #648
=> Visual bug fix - Gap between navbar and sidebar

front-end/src/Views/SearchPage.js
filter options for each result type were added as an accordion menu
sort options(alphabetical and recommended) were added
=> Search page filter and sort

android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectModel.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectsContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectsPresenter.kt
=> Display projects that user is a member, instead of owner

backend/api/serializers/comment.py, backend/api/views/comment.py
-Comment endpoint uses a different serializer while creating a new object
=> Fixed a bug that occured while creating a comment

android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectAdapter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectCard.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectsContract.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectsFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/ProjectsPresenter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/PublicationAdapter.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/project/data/ProjectShort.kt, android/app/src/main/res/layout/layout_list_item_project.xml
=> Project tags shown in users own projects.

android/app/src/main/java/com/bounswe2020group3/paperlayer/invite/UserInviteAdapter.kt
=> Fix profile picture display bug

front-end/src/Views/ProfilePage.js
=> minor bug fix for publications on profile pages of other users

backend/api/views/comment.py, backend/api/views/file.py
-Fixed a bug that caused some objects to appear multiple times in list endpoints
=> Fixed a bug in comment and file

backend/api/views/auth.py
- Now using SendGrid Email API since Google blocks our domains from sending emails
- If this method works, I will set "is_active" field of newly registered users to False
=> Using 3rd party Email API for email verification

front-end/src/Views/FileViewerPage.js, front-end/src/Views/ProfilePage.js
* deleting comments fixed
* Small visual changes to profile page
Fixes #666
=> Delete comment fix

front-end/src/Views/HomePage.js
activity feed added
change view between activity feed and projects option added
=> Add activity feed

backend/api/serializers/search.py, backend/api/views/search.py
- This filter chekcs if project's event title case-insensitively contains the given string
=> Added "project_event_title" filter to search

backend/api/views/auth.py
- System now sends verif. emails correctly!!!
- I am setting new users' is_active field to false until verification.
=> Now setting new users' is_active field to false until verification.

backend/api/serializers/auth.py, backend/api/views/auth.py, backend/backend/settings.py
- Now assigning False to is_active while creating the user object
- Modified the way that the confirmation url is created
- Added necessary constants to settings file
=> Made changes for django_email_verification library

front-end/src/Views/LoginPage.js
Controling for email verification in login page when users log in their accoounts in PaperLayer.
=> Email Verification in Frontend!

front-end/src/Views/ProfilePage.js
* Fixed follow request accepting not refreshing the page.  --- Fixed
* Collaboration request in profile page had a bug, we couldn't see project name of the request.  --- Fixed
* Projects in user's own profile only showed the projects belonging to the user, now it shows all projects the user is a member of. 
We worked on these together with @liberbey and @ynskardas.
Fixes #683 
Fixes #585
=> General bug fix

front-end/src/Views/FileViewerPage.js, front-end/src/Views/HomePage.js, front-end/src/Views/ProfilePage.js
Long project names  bug in homepage->recommendations fixed by removing max height
Fixes #685
=> long recom. name bug fixed by removing max height

android/app/src/main/java/com/bounswe2020group3/paperlayer/data/user/Profile.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/ProfileFragment.kt, android/app/src/main/java/com/bounswe2020group3/paperlayer/profile/user/UserFragment.kt
- Implemented functionality to show rating on profile page
=> [Android] Show rating on profile page

front-end/README.md
ReadMe File Changed to accomodate our customers' expectations. 
Fixes #691
=> readme file changed

backend/api/serializers/profile.py, backend/api/utils.py
-Profile returns number of raters of a user
=> Number of raters
